name: Deploy release
on:
  push:
    tags:
      - '\d+.\d+.\d+-SNAPSHOT'
      - '\d+.\d+.\d+'

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-trigger_on_tag
  cancel-in-progress: true

jobs:
  create-draft-release:
    name: ğŸ“ Create draft release
    uses: ./.github/workflows/deploy_create_draft_release.yml
    with:
      jvm-version: 17

  deploy:
    name: ğŸš€ Deploy
    uses: ./.github/workflows/deploy_jvm.yml
    needs:
      - create-draft-release
    with:
      jvm-version: 17
    secrets: inherit